apiVersion: v1
kind: Service
metadata:
  name: coworking-ms
spec:
  selector:
    app.kubernetes.io/name: coworking-ms
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5153

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-ms
  labels:
    app: coworking-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coworking-ms
  template:
    metadata:
      labels:
        app: coworking-ms
    spec:
      containers:
      - name: coworking-ms
        image: 355434700021.dkr.ecr.us-east-2.amazonaws.com/coworking-ms:7
        imagePullPolicy: Always
        ports:
        - containerPort: 5153
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: password

        envFrom:
          - configMapRef:
              name: coworking-ms-db-configmap
      restartPolicy: Always
