apiVersion: v1
kind: Service
metadata:
  name: coworking-ms
spec:
  selector:
    app.kubernetes.io/name: coworking-ms
  ports:
  - name: "5050"
    protocol: TCP
    port: 5153
    targetPort: 5153

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-ms
  labels:
    app: coworking-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coworking-ms
  template:
    metadata:
      labels:
        app: coworking-ms
    spec:
      containers:
      - name: coworking-ms
        image: 355434700021.dkr.ecr.us-east-2.amazonaws.com/coworking-ms:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
          - secretRef:
              name: coworking-ms-db-secret
          - configMapRef:
              name: coworking-ms-db-configmap
      restartPolicy: Always
